### ISSUE TITLE
v2 Local Jobs: How can I push to agent my env variable?

### ISSUE THREAD

**Issue by dharnitski** [circleci/circleci-docs#1013]
This issue is about <https://circleci.com/docs/2.0/local-jobs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/local-jobs.md>)

Local Jobs is great feature and most part of my script works out of the box.

I have one issue though. My build uses env variables. These variables are defined in host machine but not pushed to agent.

```
====>> Spin up Environment
Build-agent version 0.0.3157-32096ee (2017-04-25T19:00:21+0000)
Starting container circleci/cci-demo-go-primary:0.0.2
  using image circleci/cci-demo-go-primary@sha256:xxxxxxxxxxxxxxxx

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1493245606
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=feature-circle-ci-v2
  CIRCLE_BUILD_NUM=
  CIRCLE_BUILD_TOKEN=**REDACTED**
  CIRCLE_ENV=/tmp/.bash_env-localbuild-1493245606
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=https://dharnitski@github.com/xxxxxxxxxx
  CIRCLE_SHA1=xxxxxxxxxxxxxxxxxxxxxx
```
Is there any way to push my env variables to agent?

**Comment by michelle-luna** [comment]
Hi,

Thanks for this question, apologies for the delayed reply. Did you find the answer to your question? The following was posted to the discuss list recently, so if you still need an answer, maybe post it to this thread for additional tips for pushing to agent?

https://discuss.circleci.com/t/how-to-set-env-vars-for-local-builds-using-circleci-2-0/12714

"We don't yet have an ideal solution for that, but there is a workaround. Define which vars you want to export in a file within your repository (don't commit it - just have it in the directory) and set BASH_ENV to that filename in your config.yml. The file will be automatically sourced on each command as long as BASH_ENV is correct."

Otherwise, let me know if you have a workaround and I will add it to the 2.0 doc about local jobs.

Regards,
Michelle

**Comment by smart-alek** [comment]
Looks like there's now a comment specifically about this issue in the docs: https://circleci.com/docs/2.0/local-jobs/#environment-variables

Thank you all for playing! ;)
