### ISSUE TITLE
broken example for clojure

### ISSUE THREAD

**Issue by lsenta** [circleci/circleci-docs#1021]
This issue is about <https://circleci.com/docs/2.0/language-clojure/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-clojure.md>)

- the syntax is broken `{{ ... }}` raises !!map errors, `<< ... >>` seem's to be correct
https://circleci.com/gh/lsenta/konserve-firebase/8

- `bin/lein` doesn't exists
https://circleci.com/gh/lsenta/konserve-firebase/9

**Comment by technomancy** [comment]
Thanks for catching this. The first issue is that something changed in our use of Jekyll; that syntax used to emit `<< ... >>` but must have changed upstream. The second is actually intentional; you are meant to check in the version of `bin/lein` that you use yourself. But this should be explained more clearly.

**Comment by technomancy** [comment]
I discovered the problem with the `{{ ... }}` syntax is that it can't come at the beginning of the string; it needs a prefix before it.

Fixed here, along with a clearer explanation of when to use `lein` vs `bin/lein`: https://github.com/circleci/circleci-docs/pull/1032

**Comment by lsenta** [comment]
Thanks for the fix @technomancy 
While we're talking about Clojure on circleci, could you share/document recommendations on setting memory usage on circleci?

I keep getting random kills, messing my build status, because of OOM:
https://circleci.com/gh/lsenta/konserve-firebase/30

FWIW I've creates a docker image for clojurescript testing (lein + phantom):
https://github.com/lsenta/cljs-testing

**Comment by technomancy** [comment]
If you're running into this it's a good idea to set your `Xmx` parameter in `JVM_OPTS`. There is no one-size-fits-all answer for this since it's common to need to reserve some memory for other containers in your `docker` settings, but in this case you don't have any background containers, so setting it at `3500m` in `env` is probably the way to go.

I'll add a mention of this to the guide as well.

**Comment by lsenta** [comment]
Thank you for the details, everything is running smoothly now!
