### ISSUE TITLE
Clarify which directories are effectively cached

### ISSUE THREAD

**Issue by michipili** [circleci/circleci-docs#1344]
This issue is about <https://circleci.com/docs/1.0/how-cache-works/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/how-cache-works.md>)

The document claims “The directories which you specify in the dependencies: cache_directories section of circle.yml” are being cached but this is not true. Rather, some policy seems to be applied on these directories to determine which of them are subject to being cached.

The output of the “save cache” step looks like

```
  ✗ /home/ubuntu/.bundle
  ✗ /home/ubuntu/.cache/bower
  ✓ /home/ubuntu/.go_workspace
  ✓ /home/ubuntu/.gradle
  ✓ /home/ubuntu/.ivy2
  ✓ /home/ubuntu/.m2
  ✗ /home/ubuntu/project/cache-a
  ✓ /home/ubuntu/project/cache-b
  ✗ /home/ubuntu/project/cache-c
  ✗ /home/ubuntu/virtualenvs
```

and it turns out that directory with a ✓ are actually saved while those with a ✗ are omitted from the cache, even if these are listed in the appropirate section of `circle.yml`.

There is not even an information message hinting at why some directory is accepted and why some other is rejected.

**Comment by michelle-luna** [comment]
Thanks for this feedback, I will check about adding this message and try to find out more information and post it here.

**Comment by michipili** [comment]
Thanks, Michelle!

**Comment by marcomorain** [comment]
Hi @michipili, the `✓` and `✗` characters indicate which paths exist at the time when the caches are saved – any paths with a `✗` do not exist.

There are some subtleties here though, in CircleCI 1.0 we create a read-only BTRFS snapshot, and save caches from these. If there are any symlinks that point outside of the snapshot, then they will not be cached, since BTRFS snapshots do not recursively follow symlinks.
