### ISSUE TITLE
2.0: Move `configuration-reference` to "Reference" chapter

### ISSUE THREAD

**Issue by Dominik-K** [circleci/circleci-docs#1369]
This issue is about <https://circleci.com/docs/2.0/configuration-reference/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md>)

This page is a reference for all configuration fields (as the filename suggest). So, it would be convenient to find this page under the "Reference" chapter (in the left "table of contents" bar). The current title "Writing Jobs with Steps" is misleading.

**Comment by michelle-luna** [comment]
Thanks for this feedback, much appreciated. I hesitate to put this doc back under Reference because that category is so far below the fold that it could be easily missed by new users who will need it fairly early in the process of learning. The filename reflects the original title which is duplicated now with two category names. Titles should begin with an action verb of the gerund form and be followed by explicit terms. So, a new name that follows that convention without duplicating the words we use for the 'chapters' would be fine, but it should live in Configuration chapter because it is still the best document we have on configuration for 2.0.

**Comment by felicianotech** [comment]
This issue has been fixed in #1774.
