### ISSUE TITLE
Search Result URLs can Have Bad Anchor

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#1479]
When searching in docs using the search bar, if the URL doesn't have an anchor, `#nav-button` is added to the end of the URL. This shouldn't be the case.

To replicate, you can search in 2.0 docs for "docker", and one of the results will say "Using Pre-Built CircleCI Docker Images". Click that and the URL you'll be taken to is: `https://circleci.com/docs/2.0/circleci-images/#nav-button`.

This is related to how Algolia's docsearch scans the website. @keybits set that so he may have more insight.

**Comment by smart-alek** [comment]
@felicianotech For clarity, this sounds like undesired behavior, right? `#nav-button` should **not** be added to the URL, right?

**Comment by felicianotech** [comment]
Exactly. Last I remember, Tom said he can fix it from the Algolia side since he's admin.

**Comment by smart-alek** [comment]
@felicianotech I chatted with @keybits about this, and he mentioned that there's no real "admin" role for Algolia. We would just make a PR to our [public CircleCI config](https://github.com/algolia/docsearch-configs/blob/master/configs/circleci.json). This means that any motivated individual could fix this thing.

I also did a little bit of digging on the rogue ID that keeps getting added: `#nav-button` is an ID for the menu on mobile devices, but it's hidden for desktops. Not sure if it's being added to search results because of an Algolia bug or if it's a problem with how we're indexing docs.

I don't have any experience with Algolia, but I'm more than happy to become the guy who does. But if either @keybits or @felicianotech have a hunch about what needs to be changed, then that will lead to faster resolution of this thing.

**Comment by felicianotech** [comment]
Why the hell is our config in their repo? That's weird. I'll get a PR over to them but I feel like it being in their config makes it harder to test if I actually fixed it.

**Comment by felicianotech** [comment]
Opened a PR with Algolia to hopefully fix this: algolia/docsearch-configs#325

**Comment by smart-alek** [comment]
Everyone's config is in their repo! It's just how Algolia works. :)

**Comment by felicianotech** [comment]
My PR upstream has been merged. This issue is fixed.

Thanks for following up with this Issue Alek.

**Comment by smart-alek** [comment]
BOOOM. Nice job @felicianotech!
