### ISSUE TITLE
Scala guide config does not work for SBT > 1.0.0

### ISSUE THREAD

**Issue by RawToast** [circleci/circleci-docs#1497]
This issue is about <https://circleci.com/docs/1.0/language-scala/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/language-scala.md>)

1. There are no `.jar` artefacts for releases post 1.0 in the location the file uses to get sbt-launch. It is, however, available at Maven Central (https://mvnrepository.com/artifact/org.scala-sbt/sbt-launch/1.0.1). Note the `deb` releases are still available at Bintray.

2.  The `sbt-version` command no longer exists under 1.0, it has been replaced by `sbtVersion`

If it helps, I am using a working configuration for SBT 1.0+ using your guide as a reference but with the adjustments above:

```machine:
  java:
    version: oraclejdk8
  environment:
    SBT_VERSION: 1.0.1
    SBT_OPTS: "-Xms512M -Xmx1536M -Xss4M -XX:+CMSClassUnloadingEnabled"
dependencies:
  override:
    - sbt update
  cache_directories:
    - "~/.sbt"
    - "~/.ivy2"
  pre:
    - wget --output-document=$HOME/bin/sbt-launch.jar
      http://central.maven.org/maven2/org/scala-sbt/sbt-launch/"$SBT_VERSION"/sbt-launch-"$SBT_VERSION".jar
    - echo "java $SBT_OPTS -jar \`dirname \$0\`/sbt-launch.jar \"\$@\""
      > $HOME/bin/sbt
    - chmod u+x $HOME/bin/sbt
    - which sbt
    - sbt sbtVersion
```

**Comment by michelle-luna** [comment]
Ok, thank you, I will ask around for the author of this guide to help with this.

**Comment by smart-alek** [comment]
Hey @RawToast! Thanks for the feedback; I'm following up on @michelle-luna's mission to chat with this guide's author. But! In the meantime: have you tried playing with any Scala projects on 2.0? We're getting mighty close to EOL for 1.0 (August), so we're primarily focused on getting that up.

If you're still on 1.0 or still having troubles with Scala, definitely let me know! Otherwise, I'll be closing this issue in favor of a more up-to-date Scala guide for CircleCI 2.0. :)

**Comment by RawToast** [comment]
Sure, I have a small Scala project using SBT 1.1.0 that's I want to migrate over to CircleCI. I'll give it a go over the weekend 😸

**Comment by smart-alek** [comment]
Excellent! I'm going to close this issue in the meantime; I've got a Scala guide in the backlog for migration to 2.0, too. :)
