### ISSUE TITLE
Docs missing valid UID range

### ISSUE THREAD

**Issue by deviantintegral** [circleci/circleci-docs#1639]
This issue is about <https://circleci.com/docs/2.0/high-uid-error/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/high-uid-error.md>)

This page does a good job of explaining why high user IDs are problematic. However, it simply says that you must "change the ownership of the file" - without indicating what a _valid uid / gid range actually is_. It'd be good to include that so image maintainers don't have to guess.

(as an aside, just running `cat /etc/passwd` may be enough in many cases to find the high ID).

**Comment by smart-alek** [comment]
@deviantintegral great point! This particular doc has been a troublemaker and has come up in other issues (https://github.com/circleci/circleci-docs/issues/1786). Chances are we're going to be pulling this into Discuss or our Knowledge Base since it's a known issue.

But! Thank you for the recommendation — it's quite good and easy to fix.
