### ISSUE TITLE
Indicate what flavor of regex we're using

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#179]
I found through trial and error that our deployment section supports `(?i)` as a regex mode modifier for case insensitivity, since a customer was trying to write a case-insensitive regex.  Because there are so many regex flavors out there, would it make sense to have a regex section in our docs?  Or better yet, can we link to docs for a reference implementation that we're using?

**Comment by felicianotech** [comment]
Yes I like this. We can do a guide because there's a blog post similar to this I plan on doing anything. Then I can link back. Great idea Eric.

**Comment by smart-alek** [comment]
Closing in favor of 2.0 docs, but may still be a good idea to address regex for 2.0 if it becomes an issue.

**Comment by gladiatr72** [comment]
Ok, since this was never answered yet seems to have fairly high ranking for searches on this issue:

The solitary mention of the regex engine in use is this line in [the workflows doc](https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/workflows.md#regular-expression-support).

> CircleCI branch and tag filters support the Java variant of regex pattern matching

... which is similar to that found in libpcre (subtle syntactic differences)

**Comment by GaxZE** [comment]
I am having this issue with case sensitive and branches. I hope to have a build run on a specific regex which ignores case sensitivity. I have so far been unsuccessful. Any tips here would be excellent. 
`/some-branch/i`
`/(?i)some-branch/`
