### ISSUE TITLE
Unclear how to make splitting on time work with JUnit output...

### ISSUE THREAD

**Issue by seccubus** [circleci/circleci-docs#1837]
This issue is about <https://circleci.com/docs/2.0/parallelism-faster-jobs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/parallelism-faster-jobs.md>)

When do you use filename and when do you use classname.

How does teh circleci cli utility match the name of the test in the xml to the filenames that are produced by glob.

**Comment by iynere** [comment]
hi there, it depends on how you want to do your splitting and what data is in your JUnit XML. use `classname` if you are splitting by per-file timing data, or `classname` if you are splitting by per-class timing data. if you're having a specific issue with test-splitting, feel free to open a support ticket.

**Comment by seccubus** [comment]
@iynere that can make perfect sense if you are using JUnit from Java, but if you are a poorly OpenSource author who uses Perl to generate a JUnit and then try to get timeing based balancing working it is not helpfull at all.

If you have
```
circleci tests glob t/* | circleci tests split --split-by=timings --timings-type=classname | xargs prove --harness TAP::Harness::JUnit
```

How does the `circleci` command use what is in the classname field of the `testcase` entry in the XML to decide which names to output on the container.

Me being an open source project  means I don;t have the budget for a plan that allows me support tickets so I have to rely on the documentation and this currently isn't giving me enough information to solve this myself.

**Comment by cameront** [comment]
An answer to this question would be really helpful. Understanding how the mapping works from class->file (or even a pointer to the splitting code) would have already saved us hours of black-box debugging.

**Comment by iynere** [comment]
sorry, what is the question and what is the problem? i believe the original question about when to use `classname` vs. `filename` has been answered, so i've closed this issue. questions about our underlying source code—how we actually make test-splitting work—are certainly valid and interesting, but that doesn't really seem like an issue / bug per se...

**Comment by cameront** [comment]
One of the problems we ran into is that the splitter isn't very well documented. The question/answer that would have been specifically helpful here is:

Q: How does the circleci command use what is in the classname field of the testcase entry in the XML to decide which names to output on the container.

A: In many cases (esp where junit xml output is being generated by non-java tests) splitting by timings will not work unless the file is included in the xml and timings-type=filename is specified.

In our case, we were trying to split by timings using mocha, but the test reporter recommended by the docs (https://circleci.com/docs/2.0/collect-test-data/#mochajs) doesn't export file by default, so attempting to split by timings - as far as we can tell - won't work without reporter customization.

Having mentioned it - is there any reason that the test-splitting code can't be made public? Would've greatly decreased the amount of time we spent getting to the bottom of (this and a few other areas of) surprising behavior.

**Comment by iynere** [comment]
> which names to output on the container

what do you mean by that ?

> the test reporter recommended by the docs (https://circleci.com/docs/2.0/collect-test-data/#mochajs) doesn't export file by default

yes, the example you link to seems to be very clear about that:
```
- run:
    command: mocha test --reporter mocha-junit-reporter
    environment:
      MOCHA_FILE: junit/test-results.xml
```
> is there any reason that the test-splitting code can't be made public?

you're welcome to file a feature request for this idea: https://circleci.com/ideas

thanks !

**Comment by seccubus** [comment]
@iynere since I filed the original question I'd like to comment.

I have a perl project (yes, I'm THAT old ;) ) and I wanted to do time based splitting. 
It didn't work (for other reasons, but that is besides the point).

I was unable to find documentation that explained:
* What the differenct is between `--timings-type=classname` or `--timings-type=filename`
* If my junit.xml file contains eg. `t_01_basic_t` in the classname field, how it this interpreted back to the name of the test to run?

I relate to @cameront telling you that he needed to do 'black box debugging' because that's what I ended up dowing: trying stuff and hoping that it will "magically" work.

**Comment by cameront** [comment]
> > which names to output on the container

> what do you mean by that ?

I think it's the same question that @seccubus just clarified. Expected behavior of classname vs filename timings-type in js/mocha land.

> yes, the example you link to seems to be very clear about that:

Sorry, I wasn't clear, but I think we're talking about different "files" here. I was saying that the mocha-junit-reporter doesn't, by default, include the file attribute in the testcase/testsuite xml nodes.

HOWEVER, it appears I'm wrong, and may have just been using a version of the reporter prior to https://github.com/michaelleeallen/mocha-junit-reporter/commit/673aef95ebd56d90bb368f12ca3128b2c523d750

So ignore me - sorry for the noise.

> you're welcome to file a feature request for this idea: https://circleci.com/ideas

Submitted an idea to open source the timing/splitting code. Thanks for that suggestion.
https://circleci.ideas.aha.io/ideas/CCI-I-244

**Comment by thomasmatecki** [comment]
Any chance this can be re-opened? I'm having the same issue as in https://github.com/cypress-io/cypress/pull/3960 and agree...
> One of the problems we ran into is that the splitter isn't very well documented.

The important question for me is, **Where does circle expect timing information to be in a junit XML, if I wish to parallel by file?** 

I have an report like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="16.1050" tests="3" failures="0">
  <testsuite name="Root Suite" timestamp="2022-09-30T15:00:44" tests="0" file="cypress/e2e/SomeFeature.cy.ts" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Describe Some Part of Something" timestamp="2022-09-30T15:00:44" tests="3" time="16.1050" failures="0">
...
    </testcase>
  </testsuite>
</testsuites>
```

This doesn't work, ostensibly because the `testsuite` with a `file` (is that the attribute circle expects?) has `time=0.00` and no `tests`. So it must be something else. 

Here's a guess:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="16.1050" tests="3" failures="0">
  <testsuite name="Root Suite" timestamp="2022-09-30T15:00:44" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite 
        name="Describe Some Part of Something" 
        timestamp="2022-09-30T15:00:44" 
        tests="3" 
        time="16.1050"
        file="cypress/e2e/SomeFeature.cy.ts" 
        failures="0">
...
    </testcase>
  </testsuite>
</testsuites>
```

It'd be good if this was documented. Right now I have to spend time and Circleci credits trying to figure out the format the platform expects. It'd be much easier to justify using CircleCI over your competitors if this was more seamless.

**Comment by lucaciraolo** [comment]
@thomasmatecki I'm having the same issue where no timing data is found for my cypress tests I think because the time="0". Did you figure out where the file path or timings need to be moved to in the xml?

Sorry for resurfacing an old thread but thought it was worth a shot before spending ages trying various combinations....

**Comment by thomasmatecki** [comment]
@lucaciraolo Yes, there's more info in this issue: https://github.com/circleci/circleci-docs/issues/7421. The docs were updated. I did need to transform the xml report that is output by cypress with XSLT to add the `file` attribute to each `testsuite`. So something like this, IIIRC:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="16.1050" tests="3" failures="0">
  <testsuite name="Root Suite" timestamp="2022-09-30T15:00:44" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite 
        name="Describe Some Part of Some Feature" 
        timestamp="2022-09-30T15:00:44" 
        tests="3" 
        time="16.1050"
        file="cypress/e2e/SomeFeature.cy.ts" 
        failures="0">
...
    </testcase>
  </testsuite>
</testsuites>
```

Hazy memory: It may also have been possible to re-org our cypress tests such that useful attributes were attached to the _Root Suite_, but this seemed like an imposition on the folks writing tests.
