### ISSUE TITLE
RE: jekyll/_docs/configuration.md

### ISSUE THREAD

**Issue by seanli310** [circleci/circleci-docs#199]
What's difference between 3 stages of dependencies( pre, override, post). And what is the thing being overridden?
And What's difference between 3 stages of test( pre, override, post).  And what is the thing being overridden?
And What's difference between 2 stages of machine( pre, post).

**Comment by felicianotech** [comment]
`pre` means before the section. This is where you can run commands in that section before the normal stuff in that section happens.

`post` means after the section. This is where you can run commands in that section after the normal stuff in that section happens.

`override` is where you run your own commands instead of CircleCI running the commands it thinks you might want. This is called CircleCI Inference. For example, if you have a Ruby project and CircleCI sees that you have a `Gemfile`, CircleCI Inference will try to install the gems listed in the `Gemfile` for you automatically. This happens in the dependencies section. If you don't want to do this, you would use `override` in dependencies and write your own commands to run instead.

Does that help?

**Comment by keybits** [comment]
Closing this. Feel free to reopen if the docs need to be clearer.
