### ISSUE TITLE
Why not provide a UI (button?) for that ?

### ISSUE THREAD

**Issue by sfermigier** [circleci/circleci-docs#2079]
This issue is about <https://circleci.com/docs/2.0/config-translation/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/config-translation.md>)

Asking the user to guess the URL or to use your API isn't really friendly.

**Comment by smart-alek** [comment]
@sfermigier You are absolutely correct, sir! It is quite unfriendly of us. You stumbled across a fairly new feature that is almost certainly going to receive some love in the future.

As a continuous shop, this is the kind of thing we struggle with sometimes — providing _some_ functionality and then adding to it later. We _do_ have a button planned, but we want to hook it up to something that's working properly, so that's the reason you're seeing the doc in this weird state.

Maybe you'll hate this, but one excellent way of getting visibility and putting pressure on us is to pop over to our [Ideas](https://circleci.com/ideas/) and submit your request. Other users can vote, and eventually we succumb to your demands or shout that we're not doing it. It's great fun.

But! In the meantime, I'm closing this issue because this isn't something that we can fix in docs land.
