### ISSUE TITLE
Snap use

### ISSUE THREAD

**Issue by txomon** [circleci/circleci-docs#2108]
Hello, your guide suggests using snap to install docker and circleci. This has a high chance of interferring with the probably already existing docker packages in the system. For example, the instalation of the docker snap has broken my docker installation.

I would suggest you remove the use of snap, or at least, have a big warning on what can it happen with existing setups.

https://circleci.com/docs/2.0/local-cli/#installing

**Comment by felicianotech** [comment]
@txomon How has it broken your Docker installation?

**Comment by txomon** [comment]
docker service stopped responding and had to reinstall and restart docker service from my package manager

**Comment by felicianotech** [comment]
How did you install Docker previously? Their official repository? The distro repository? Something else?
 Also, what distro and version are you using?

I'm asking because I have Docker installed via the official repo on Ubuntu 17.10 and also have the snap and there's no issues. I will be altering the install directions for the Local CLI with more information however so thank you for opening this Issue.

**Comment by txomon** [comment]
Sorry, I feel like I am not giving enough information. I use archlinux, and is just docker package.

I would recommend just removing the docker installation from the guide, pointing people towards installing docker from the project webpage, as docker is already packaged in many of them.
