### ISSUE TITLE
Add link for context

### ISSUE THREAD

**Issue by meetar** [circleci/circleci-docs#2316]
This issue is about <https://circleci.com/docs/1.0/browser-testing-with-sauce-labs/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/browser-testing-with-sauce-labs.md>)

> you can use Sauce Labs in the usual way

It would be great to have a link here to "the usual way" for context, for those who don't already know what that is :)

**Comment by smart-alek** [comment]
Hey @meetar, fair enough, and thanks for submitting this issue!

Due to the upcoming 1.0 EOL, we're trying to keep updates to 1.0 docs to a minimum. If you can, head to the [2.0 version of Sauce Labs docs](https://circleci.com/docs/2.0/browser-testing/#sauce-labs), and let us know if you're having trouble there. Thanks!
