### ISSUE TITLE
Question: Git push to protected branches

### ISSUE THREAD

**Issue by awentzel** [circleci/circleci-docs#2322]
This issue is about <https://circleci.com/docs/1.0/npm-continuous-deployment/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/npm-continuous-deployment.md>)

Are there any exceptions to pushing up to git after NPM publish.  For example, can we push to a protected Git branch on GitHub? What about committing to that same branch?

**Comment by smart-alek** [comment]
Hey @awentzel! Thanks for submitting this issue.

We're actually nearing the end of our support for CircleCI 1.0. It may not answer your questions above, but have you taken a look at the [CircleCI 2.0 article](https://circleci.com/docs/2.0/deployment-integrations/#npm) about using NPM? From a cursory glance, it looks eerily similar to the 1.0 doc you linked.

I also found [this document](https://circleci.com/docs/2.0/workflows-waiting-status/) about workflows waiting because of issues with GitHub's protected branches.

Let me know if either of those help, otherwise we can keep digging into this!

**Comment by smart-alek** [comment]
Hey @awentzel — since I didn't hear anything else from you, I'm going to close this issue. If you've got any questions about the 2.0 documents I linked, definitely reach out. Thanks!

**Comment by smart-alek** [comment]
Just to follow up and close the loop here:

It is possible to push to a protected Git branch on GitHub, but it requires 1) admin access, and 2) branch protection to be set to allow admins to override. Check out the [official GitHub article](https://help.github.com/articles/working-with-protected-branches/) on working with protected branches for more information. Best of luck!
