### ISSUE TITLE
Best usage of splitting tests with parallelism?

### ISSUE THREAD

**Issue by aarondack** [circleci/circleci-docs#2444]
Hey there, 

I don't seem to be getting any gains by splitting my tests and running in parallel. This leads me to believe I'm doing something wrong. This is what I'm running.

`circleci tests glob tests/**/*.js | circleci tests split --split-by=filesize | yarn run test`

I've been rummaging through the docs, but was looking for a concrete way of accomplishing this. Thoughts? 

Also, I know this might be borderline a support ticket, but I ended up placing it here as I'm looking for an example we could add to the docs.

**Comment by aarondack** [comment]
Hey @smart-alek sure do! 

This is what my `config.yml` currently looks like. 

```
test:
	parallelism: 4
	steps: 
		- // some previous steps
		- run:
			name: Run test
			command: circleci tests glob tests/**/*.js | circleci tests split --split-by=filesize | yarn run test
```

I was able to find the splitting test files section in the docs -- but was hoping for a more concrete example. 

Does everything look good up there?

**Comment by smart-alek** [comment]
Hey @aarondack, thanks for the quick response!

So you've set the `parallelism` key, and that command **looks** like it should I am noticing one small difference in your command and the docs: do you think your globbing pattern should have quotes around it?

I really hope that's not it, but regardless — shame on us because we have examples with and without quotes! 😬

**Comment by smart-alek** [comment]
One more question for you @aarondack: are you running the `test` job in a Workflow?

**Comment by smart-alek** [comment]
Yet another question @aarondack!

Have you tried something like:

`yarn run test $(circleci tests glob tests/**/*.js | circleci tests split --split-by=filesize)`

The difference here is that you might be piping the results of your test splitting to `yarn` as stdin — rather than explicit arguments. If that works for you, let me know! In either case, we'll get it documented to save future folks from this. :)

**Comment by aarondack** [comment]
Hey @smart-alek, 

Okay! I tried a few things. I converted the globbing pattern to use strings, and here's how I'm executing it in a workflow. 

- deploy:
	requires:
		- test

Butttt with all that being said, it looks like that command you posted above ^ has seemed to work 🙌 

Thanks so much!

**Comment by smart-alek** [comment]
BEAUTIFUL. 👍👍👍
