### ISSUE TITLE
environment both list and map?

### ISSUE THREAD

**Issue by Bkucera** [circleci/circleci-docs#2445]
This issue is about <https://circleci.com/docs/2.0/configuration-reference/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md>)

Environment is documented as a `Map`, however there are examples _everywhere_ as a List. Even on the same page, see screenshot.

![image](https://user-images.githubusercontent.com/14625260/41928063-fd64da82-7941-11e8-8696-4539b62a4368.png)

Can `environment` be both a list and a map?

**Comment by smart-alek** [comment]
Hey @Bkucera! Great question — I've confirmed with engineering that this can indeed be both a map and a list. We haven't decided whether or not to change the definition in the reference yet — it **should** only exist as a map, but folks use it as a list often enough that we'd rather force build breakages.

Would this be more clear if the examples across docs all used maps instead of mixing types?

**Comment by Bkucera** [comment]
Thanks for that! Yes, it would help if examples were all changed to `Map` :+1:
