### ISSUE TITLE
what does "review the support bundle" mean?

### ISSUE THREAD

**Issue by acthp** [circleci/circleci-docs#2569]
# Location
https://circleci.com/docs/2.0/troubleshooting/

# Explanation
The term is undefined, and a search of "support bundle" returns only this single instance of the term anywhere in the docs.

**Comment by smart-alek** [comment]
Hey @acthp, thanks for submitting an issue! Definitely see the confusion here. How did you make your way to this document? Are you using cloud or server?

**Comment by acthp** [comment]
Um.... no idea. We're using the free-for-open-source plan to build this interactive tool for cancer researchers:

https://xenabrowser.net/heatmap/?bookmark=4e74d5763970ebc5821878cf111e0f4a

The actual problem I was hitting was that after converting config to 2.0, nothing would happen when I pushed a commit. After too much reading of docs & poking at things, I found that the "Workflows" tab (which I'd never used before... 2.0) was emitting incomprehensible error messages about the yaml. With only this to go on, I tweaked whitespace in the yaml until things started building. yaml whitespace is a nightmare.

So... in addition to documenting what "review support bundle" means, I recommend adding something to the "troubleshooting" page about "check the Workflows tab, which maybe you've never seen before", and any other places where errors might be silently logged. Or better: since email notifications are enabled, send an email on yaml errors! That's exactly the sort of the thing that email notifications are for!

I also recommend documenting the yaml-schema-error message format that appears in the Workflows tab. It looks like the output of some clojure schema library, but I couldn't identify which one. Not spec, and not herbert, I think, but I stopped looking after those two.

... also, I noted after getting this far that the workflow could *still* fail on yaml schema problems, later in the build: I added a "deploy" job to the workflow, which reported some sort of schema error in the "jobs" tab (and also sent email notification, which is great). It would be so much nicer to have all the schema errors reported in one place, in a readable, or at least documented format.

**Comment by acthp** [comment]
oh, and I found the document linked in the left nav bar in the docs, under "Troubleshooting"

**Comment by smart-alek** [comment]
@acthp this is fantastic feedback — thanks for taking the time to write it up.

I'm hearing a couple of things here (and catch me if I miss something):

1. The "Troubleshooting" link you clicked on is actually for our Server product. It sits behind your firewall instead of running in the cloud. From what you've written, it sounds like you're using the cloud version — and this is good! What is not so good is that the "Troubleshooting" link was enticing enough to click on — even though it was listed under the "Server Administrators" heading. And that is something the docs team can fix! 🎉 

2. As far as the YAML formatting and error surfacing goes, we can definitely add some documentation on (1) using the Workflows tab, and (2) the schema error format we're using in the Workflows tab.

3. In terms of **collecting** all the schema errors in one place, that is excellent feedback! We've already got a similar project in the works right now, but I've linked this issue for their enlightenment.

Keep an eye out for those docs updates! :)
