### ISSUE TITLE
where to run debug steps

### ISSUE THREAD

**Issue by acthp** [circleci/circleci-docs#2570]
# Missing Information
The trouble-shooting page has a list of steps to take if builds are not running, like

```
sudo docker logs dispatcher
```

but, well... builds are not running. Where would I run this command? There's no rebuild-with-ssh option if there's no build. Where am I supposed to log in?

https://circleci.com/docs/2.0/troubleshooting/

# Already Looked
https://circleci.com/docs/2.0/troubleshooting/

# Potential Locations
https://circleci.com/docs/2.0/troubleshooting/

**Comment by smart-alek** [comment]
Hey @acthp, I know we've got a separate convo going in #2569, but I think these two issues might be related. This command should be run in a private server installation of CircleCI. For your case, this wouldn't make sense since you're running everything in the cloud.

So! I think the **real** issue is that this Troubleshooting document is not really helpful to cloud users, but is confusingly suggested and prominently displayed in the navigation bar.

Agree? Disagree?

**Comment by acthp** [comment]
Oh! Yeah, I didn't understand that it was about running on private hardware. Regarding the heading, I'm not sure I even saw it. I did ^f troubleshooting, and clicked the link. I'd seen the word "troubleshooting" somewhere previously, maybe in the 2.0 faq, and was trying to finding it again after I couldn't get the build started.
