### ISSUE TITLE
Rerun build with SSH: No SSH key is found

### ISSUE THREAD

**Issue by timc13** [circleci/circleci-docs#2594]
# Missing Information
When running a build with SSH.  I've gotten the following error:
```
Failed to enable SSH
No SSH key is found. Please make sure you’ve added at least one SSH key in your VCS account.
```
and the documentation on https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/ssh-access-jobs.md does not address how to fix this.

It's quite confusing because there seems to be many different ways to add SSH keys (Checkout SSH Keys? SSH Permissions? `add_ssh_keys` ?)

# Already Looked
https://circleci.com/docs/2.0/add-ssh-key/
https://discuss.circleci.com/t/unable-to-build-with-ssh/22372/3

It's still unclear what SSH key is necessary for this to work...

# Potential Locations
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/ssh-access-jobs.md

**Comment by smart-alek** [comment]
Hey @timc13, thanks for submitting an issue!

So, in this case, "Checkout SSH keys" is what you need, and you'll want to generate an SSH key you're using with GitHub or Bitbucket, then add that to CircleCI.

"SSH Permissions" is specifically for keys you use to deploy your application.

`add_ssh_keys` is a field in `config.yml` specifically for injecting the SSH key you added to the project to the container itself.

I'm sure a lot has happened since you filed this (sorry for the delay!), but can you remember if you found [this GitHub link](https://help.github.com/articles/error-permission-denied-publickey/) in the [original document](https://circleci.com/docs/2.0/ssh-access-jobs/#debugging-permission-denied-publickey) you were looking at?

**Comment by timc13** [comment]
Perhaps, but my original problem precluded the solutions on that document - there was no SSH key and thus no `Permission denied (publickey)` message

My problem, was that I had no idea I had to create a "Checkout SSH Key" for "Rerun job with SSH" to work.  I don't think you mention that anywhere as a requirement for debugging with SSH.

Thus, I'm suggesting to put this information here: https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/ssh-access-jobs.md

**Comment by timc13** [comment]
Perhaps, but my original problem precluded the solutions on that document - there was no SSH key and thus no `Permission denied (publickey)` message

My problem, was that I had no idea I had to create a "Checkout SSH Key" for "Rerun job with SSH" to work.  I don't think you mention that anywhere as a requirement for debugging with SSH.

Thus, I'm suggesting to put this information here: https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/ssh-access-jobs.md

**Comment by smart-alek** [comment]
Got it — so you were trying to debug via SSH, but didn't realize you would need an SSH key from you VCS to do that. Did the error message you saw help you at all? I can definitely see the disconnect between creating a SSH key for you VCS account and "Checkout SSH Key".
