### ISSUE TITLE
Update versions for Cocoapods and Xcode (_cci1/ios-builds-on-os-x.md)

### ISSUE THREAD

**Issue by yousefhamza** [circleci/circleci-docs#271]
Suggested updates:
- Cocoapods version to: 1.0.x
- And listed UUIDs is for machine with XCode 7.3

**Comment by smart-alek** [comment]
@yousefhamza you caught us! 😬 

There are most likely dozens of places where we are using a non-current version of a piece of software. But! instead of tracking those down in our 1.0 docs, we're focusing on making our [2.0 docs](https://circleci.com/docs/2.0) as accurate as we can. Thanks for the catch and stay tuned for our next iteration!
