### ISSUE TITLE
Triggering specific jobs/workflows via API in v2 doesn't work

### ISSUE THREAD

**Issue by doublejosh** [circleci/circleci-docs#3219]
# Locations
https://circleci.com/docs/2.0/api-job-trigger/#section=jobs

# Details
The doc explains how you can trigger specific jobs via API. However the only job that is ever triggered is `build` regardless of the parameter.

### Attempt...
https://circleci.com/api/v1.1/project/github/(COMPANY)/(REPO)/tree/(BRANCH)?build_parameters[CIRCLE_JOB]=(JOB_NAME)&circle-token=(MY_TOKEN)

_I've used parenthesis for variables since there's an all caps bracket parameter already in the API example._

### API Response
"Cannot find a job named `build` to run in the `jobs:` section of your configuration file."

## Background?
Seems like this API endpoint might be newer and was created through some forum conversion...
https://discuss.circleci.com/t/trigger-workflow-through-rest-api/13931/48

**Comment by kenperkins** [comment]
I discovered that using the [API doesn't follow workflows at all][1], and [thus must have a job named `build`][2].

[1]: https://support.circleci.com/hc/en-us/articles/115014763287-Run-builds-with-local-config-file
[2]: https://circleci.com/docs/2.0/configuration-reference/#jobs

**Comment by teesloane** [comment]
Hi there @doublejosh. Sorry about the late reply on this one! I tried to replicate the issue on a [dummy project](https://github.com/teesloane/haskelletor), and seemed to get it working. Here was my process.

So I made a curl request based on [this doc:](https://circleci.com/docs/2.0/api-job-trigger/#overview):

```sh
curl -u <my_token>: \
     -d build_parameters[CIRCLE_JOB]=test \
     https://circleci.com/api/v1.1/project/github/teesloane/haskelletor/tree/master
```

Which triggered the job `test` in my workflow. 

![image](https://user-images.githubusercontent.com/12987958/57157633-453f6e00-6daf-11e9-87fe-134bb3d25b22.png)

Have you had any luck with this since?

**Comment by doublejosh** [comment]
Had to use this...

https://circleci.com/api/v1.1/project/github/dronedeploy/landing_page/tree/stage?circle-token=[TOKEN]


josh

_____________________________
sent though a series of tubes...
if (calling === best) { 206.801.0SEA (0732) }
else { email back }

http://twitter.com/doublejosh
http://doublejosh.com

_/▔﹀\_︿╱﹀╲/╲︿_/︺╲▁︹_/﹀\_︿╱▔︺\/\︹▁╱﹀▔╲︿_/︺▔╲▁︹_/﹀▔\⁄﹀\╱﹀▔︺\︹▁︿╱\╱﹀▔╲︿_/︺▔╲▁︿/\︿╱\︿︹_/▔﹀\_︿╱▔︺\︹╱﹀▔╲︿_/︺▔\╱﹀╲▁︹_/﹀\_︿╱▔︺\︹▁︿⁄╲︿╱﹀╲︿_/︺▔╲︹_/▔﹀\
