### ISSUE TITLE
What's allowed for "condition"?

### ISSUE THREAD

**Issue by jamesarosen** [circleci/circleci-docs#3276]
# Location
https://circleci.com/docs/2.0/reusing-config/

# Explanation
The document has examples of the form
```yml
- when
    condition: << parameters.preinstall-foo >>
```
but it doesn't describe what the allowed values of `condition` are. Is
```yml
- when
    condition: "[ ! -f ./some/file.txt ]"
```
valid? Will it only run the `when` block's `steps` when `some/file.txt` does not exist?

**Comment by mikegee** [comment]
@jamesarosen have you had any success running code in the condition? I can't get it to evaluate to `false`. I think it is interpreting the non-empty string as truthy and not evaluating it.

**Comment by mikegee** [comment]
https://circleci.com/docs/2.0/configuration-reference/#the-when-step-requires-version-21 makes me think this is impossible, even though the PR closing this issue says otherwise.

**Comment by thomasr8** [comment]
@mikegee and @jamesarosen . I will work on this today to make the documentation more clear. @jamesarosen , I believe you are right that the code evaluates a non-empty string as true. I will verify with the API team and then make changes to the documentation as needed to clarify. Thanks for the help!

**Comment by eddiewebb** [comment]
@mikegee / @jamesarosen - The `condition` of orbs only consider parameter values, it is not possible to evaluate any custom/scripted logic. That would need to be moved into the step itself using bash if/else statements.

If the parameter type is boolean, than the value must be true. If parameter type is string, then an empty value will be false.

Here are a few examples in action.

The gradle orb uses will use an existing test report path if provided, or otherwise generate one in a temp directory:
https://github.com/CircleCI-Public/circleci-orbs/blob/ac1f91f869695072858f0398df75c8cd1ebfc65a/src/gradle/orb.yml#L117

The Heroku orb will use a boolean parameter to decide if it should use maintenance mode:
https://github.com/CircleCI-Public/circleci-orbs/blob/40d83d44178c4fc1b1dc3cb34383980aab1e2215/src/heroku/orb.yml#L149

**Comment by cjw296** [comment]
It would be super useful if non-empty strings would evaluate as true, it's super confusing that they don't. Where's the best place to raise this?
