### ISSUE TITLE
Proposal: A Orb Configuration Reference

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-docs#3434]
Someone asked if there was an Orb Configuration Reference, similar to the [CircleCI Configuration Reference](https://circleci.com/docs/2.0/configuration-reference/).

This got me thinking that maybe this would be a useful reference to have. CircleCI configuration v2.1 and orbs go hand-in-hand thus the config syntax is mostly the same. There are areas that are only relevant to one or the other though.

Examples of keys in orbs that isn't relevant to general config:
- the top-level `description` key. In orbs, this provides a description for the orb as a whole that is displayed in the orb registry. This is needed for orbs.
- I can foresee new keys in the future that might be used for orbs/the registry that don't apply to general config.

Examples of keys in configuration reference not relevant to orbs:
- workflows - and everything under it

Thoughts? Anyone want to take this on?

**Comment by KyleTryon** [comment]
I would very much like to see more parity between our docs, config reference, workflow reference, orb reference. Make everything easy and predictable. Big +1 from me.

**Comment by michelle-luna** [comment]
I put the 2.1/orbs keys in the config reference because they are additive and there are only 4 new keys for 2.1, those sections then point to the re-using config and creating orbs documents for the examples and further details (which also include workflows examples). So, I think we have this covered, but in a bit different way --I wanted to use the config reference because it is so heavily referred, but don't want to put everything about orbs there because it is essentially optional.

**Comment by teesloane** [comment]
@KyleTryon  - would this essentially mean breaking up the configuration reference? 

This might be something we could all talk about at the next docs meeting to make sure we're on the same page.

**Comment by felicianotech** [comment]
My proposal isn't to touch as configuration reference at all.

It's to create an orb reference.

**Comment by michelle-luna** [comment]
we have this here now: https://circleci.com/docs/2.0/reusing-config/#section=configuration
