### ISSUE TITLE
RE: jekyll/_docs/config-sample.md

### ISSUE THREAD

**Issue by Erowlin** [circleci/circleci-docs#346]
Please add a section on how to manually load this file to the current SSH session. 

Right now, there is no way (at least it's not documented) to load environment variables wrote in the circle.yml when you SSH to your build container to debug. 

Thanks.

**Comment by felicianotech** [comment]
Hi,

Can you please provide more detail on exactly what you are trying to do?

**Comment by Erowlin** [comment]
I try to debug a spec that is failing on CircleCI and not on my localhost. 

To do so, I need to be able to run `bundle exec rspec spec` with all the environment variables that are present in the `circle.yml` (I have more than 50). 

When you SSH to a container, the session does not contain the Environment variable loaded. I find a way to load all those environment variables and others parameters I've wrote in the circle.yml. 

The quick and dirty workaround I've found was to use the node0 (`ssh node0`), this one contained all my environment variables. 

If this is the proper way to do it, it should be documented.

**Comment by felicianotech** [comment]
Hmm, are you using multiple containers? Just tried this on a single container project and it seems to work.

**Comment by felicianotech** [comment]
Just tried with multiple containers and it still works. They only thing I can think of is that you're logging in via SSH because the following step in the machine phase: `Exporting env vars from circle.yml (0)`

Could you try again, pausing for a few seconds? Or, if you can watch the web UI, wait until after the step I mentioned and then SSH in?
