### ISSUE TITLE
Example of Publishing to Github Package Registry

### ISSUE THREAD

**Issue by tenjojeremy** [circleci/circleci-docs#3469]
# Missing Information
Give a brief overview of the information you were looking for.

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.

# Potential Locations
Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document.

**Comment by dvidsilva** [comment]
@tenjojeremy You should be able to create a .npmrc file, store your github token in a variable, and publish.

Login in your computer to generate a token, that looks like this:

```
@codertocat:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=bf87b0f9a58d1b444130c64ff
```

You have to recreate it, like:

```
 - run:
          name: Add NPMRC
          command: |
              echo "@codertocat:registry=https://npm.pkg.github.com/" > ~/.npmrc
              echo "//npm.pkg.github.com/:_authToken=\"$GITHUB_AUTH_TOKEN\"" >> ~/.npmrc
              npm set @codertocat:registry https://npm.pkg.github.com
```

Then after you can run `npm publish`. But if a new push and a build is triggered, the publish will fail because you can't publish the same version again.

You can find more info in the github package registry help https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry#configuring-a-package-scope-using-publishconfig-in-packagejson 


Happy to make a PR if that makes sense, and it helps

**Comment by sirajulm** [comment]
@dvidsilva The documentation provides two solutions for tokens to publish a package to Github Packages.
I dont like using a personal access token when publishing from a Team project. But as per the `GITHUB_TOKEN` option  is only available in Github Actions. I  tried looking into github settings to generate a project level token but couldnt find it.
Any help would be appreciated. Thanks
