### ISSUE TITLE
Update URL to use for viewing branch statuses on all repos (_cc1/polling-project-status.md)

### ISSUE THREAD

**Issue by ljwagerfield** [circleci/circleci-docs#355]
Which URL do I use to view the status of all branches on all repositories?

The documentation implies the following URL should work...

`https://circleci.com/cc.xml?circle-token=:circle-token`

.. but this only returns the state of the `master` branch for each repository.

**Comment by smart-alek** [comment]
@ljwagerfield this is a bit late, but have you tried substituting your own CircleCI token for `circle-token` in the URL?

**Comment by reebalazs** [comment]
What's the status of this issue? The ticket is closed, but the feature is still broken as of today. Only the status of the master branch is returned, I have not found any way to poll for the build results of all branches. If this is not intended to work (i.e, there is simply no way to poll the build status for all branches), then this should be clarified in the documentation.

**Comment by smart-alek** [comment]
Hey @reebalazs, sorry for the radio silence on this one. I **believe** we closed this because it was specific to CircleCI 1.0. Are you looking at any 2.0 docs?

If not, you might find what you're looking for in [this section](https://circleci.com/docs/api/v1-reference/#recent-builds) of the API document. If not, let me know, and we'll get this queued up!

**Comment by reebalazs** [comment]
Hi @smart-alek, thanks for looking at this! Originally I used this on CircleCI 1.0, and it was failing. Just a few days ago, I migrated this stuff on CircleCI 2.0, so now I am trying to use it on 2.0 and it fails the same way.

I've never found the link in the document that you've just quoted, and it probably would have solved my problem on Circle 1, but since Circle 1 is deprecated and closed, my interest is now to make this work on CircleCI 2.0. That said, besides fixing the results to reflect all branches instead of master only, I think it _might_ make sense also to change the status in a way that it polls the workflow results instead of the job results, or provide an alternate way to poll workflows, so that the users decide whether to poll the results for whole workflows or individual jobs only. (To me workflow results seem more useful at the first sight, but I might be wrong.)

Thanks again!

**Comment by smart-alek** [comment]
So would you agree that this is more of a feature request than a docs request? ;) I'm fully onboard with your points: getting results for all branches is preferable, as is polling results for complete workflows.

However! This is not something we can fix from a docs perspective. What I **can** do is make our product folks aware of this. Sound like a deal?

**Comment by reebalazs** [comment]
Alright, please let the feature people notified. Indeed this is not a doc only request now, but please make sure that you include something in the documentation for 2.0 to indicate how this can be carried out on 2.0, or that the feature is being developed and expected to work at a later point.
