### ISSUE TITLE
It isn't clear if multiple contexts are supported or not

### ISSUE THREAD

**Issue by jaygorrell** [circleci/circleci-docs#3703]
# Location
https://circleci.com/docs/2.0/configuration-reference/#context

# Explanation
This makes it sound like multiple contexts are somehow supported. Calling out "unique" naming on this page isn't really relevant to this section and should be left out.

**Comment by michelle-luna** [comment]
Multiple contexts are supported and they must have unique names.

**Comment by BotanMan** [comment]
@michelle-luna Hello
Could you let me know how can I use multiple context, there is no proper descrption in the document, should I put it as `context1 context2` or `context1, context2` or somehow else?

**Comment by ideasculptor** [comment]
multiple contexts are supported attached to a single job? I'm pretty sure that's what is being asked for here. Using different contexts for separate jobs is fairly obvious.  If multiple contexts attached to a single job (in order to avoid duplicating values into multiple contexts) is possible, the syntax is non-obvious.

**Comment by roopakv** [comment]
multiple contexts with a single job is not possible at the moment. :(

this is mentioned somewhere specifically in the docs too

**Comment by jaygorrell** [comment]
@michelle-luna Can you please re-open this? As others have stated, it was closed in error.

**Comment by ideasculptor** [comment]
If not multiple contexts, having one context inherit from another context so that we can just use the child context would be hugely useful for avoiding duplication of env variables or forcing lots of unnecessary variables to be set for many jobs would be a big win.

If I have a job that does some AWS stuff and tests against a particular db and is running for a particular environment, I'd be much better off applying 3 contexts to that job than having a context which has variables for AWS access and db access and all of the per-environment variables, since that means that I would need the full context defined for at least all 3 environments, so a change to AWS credentials now requires updating AT LEAST 3 separate contexts instead of just the aws context.  Whether I get there by applying 3 contexts to a job or defining a 4th context that just does `include context1, include context2, include context3` via some syntax and then assigning context4 to the job isn't terribly relevant.  Allow later inclusions to override values defined in earlier inclusions and you've basically got 100% of the functionality everyone is looking for.

**Comment by camerondubas** [comment]
Here's a relevant feature request. https://ideas.circleci.com/ideas/CCI-I-761

**Comment by ospin-webapp** [comment]
Contexts take list arguments as I understand:
```
context:
  - context-a
  - context-b
  ```
