### ISSUE TITLE
Duplicate content on pages regarding supported languages

### ISSUE THREAD

**Issue by mvxt** [circleci/circleci-docs#3801]
# Locations
We've got two pages that essentially document the same information. Perhaps we should pare it down to one page and link to one from the other:

[Supported Languages](https://circleci.com/docs/2.0/demo-apps/#section=welcome)
[Tutorials](https://circleci.com/docs/2.0/tutorials/#section=configuration)

# Conflict Description
Both pages detail a variety of example configuration/projects for various different languages and frameworks customers are building on our platform.

We could probably remove the table from the "Supported Languages", make the description higher level, and then link to our tutorials page.

**Comment by michelle-luna** [comment]
Hi, 
This duplication is on purpose because different users will come to these two page at different times for different reasons. (One to decide whether they can use our product, one when they are needing a tutorial after getting stuck). In both cases we want the links to the various examples.
Thanks!
Michelle
