### ISSUE TITLE
How to unlock macOS Keychain

### ISSUE THREAD

**Issue by LaVielle** [circleci/circleci-docs#3829]
# Missing Information
I am using fastlane to build my iOS app. I am running into signing issues, with messages such as
```
security: SecKeychainItemImport: User interaction is not allowed.
```
```
There are no local code signing identities found.
You can run `security find-identity -v -p codesigning /Users/distiller/Library/Keychains/login.keychain-db` to get this output.
```
```
Could not find the newly generated certificate installed
```

My best bet is that the  Keychain is locked and I need to unlock it (e.g. with fastlane `unlock_keychain`)

**How do I do that?**

# Already Looked
https://circleci.com/docs/2.0/ios-codesigning/
https://discuss.circleci.com/t/ios-code-signing/1231

# Potential Locations
https://circleci.com/docs/2.0/ios-codesigning/

**Comment by marcomorain** [comment]
Hi @LaVielle 

I'd like to get to the bottom of your particular issues through the support system so that we can get your project building and code-signing correctly. Would you be able to email support@ and we can dig into the specific issues with some more context (the URLs of your builds, etc).

Once we have the issue resolved, we will of course update the docs.

Marc

**Comment by LaVielle** [comment]
I ended up getting my build to work by modifying my Fastfile:

I used to have steps `match`, `get_certificates`, `get_provisioning_profile`, `increment_build_number`, and then other non problematic steps.

Now I go straight from the `match` step to `increment_build_number`, and the code signing issues are gone.

I'll close this issue as it turns out I don't need to unlock the keychain. However, more examples on how to combine CircleCi/Fastlane would be appreciated.

Thanks!
