### ISSUE TITLE
Confusing Migration Docs for Azure DevOps

### ISSUE THREAD

**Issue by BaibhavVishal123** [circleci/circleci-docs#4065]
# Location
A link to the document that is unclear.
https://circleci.com/docs/2.0/migrating-from-azuredevops/#section=getting-started

# Explanation
Started with CircleCI, dont know its limitations and capabilities. But if I am not wrong, CircleCI should be able to clone Azure git repository. Misleading statement in the opening para itself.

Plus it doesn't list the benefits why CircleCI over Azure, is it cost or some other niche tool without which a team cant' manage. And why Enterprise git account????

**Comment by rosieyohannan** [comment]
Hi @BaibhavVishal123, thanks for getting in touch. I think part of the problem here is the formatting of the doc - links are provided for how to import to GitHub and Bitbucket, then some steps are provided in the doc for importing to GitHub *Enterprise*, so GitHub and GitHub Enterprise are both covered - I will look in to fixing this to make it clearer. 

Currently for CI, CircleCI integrates with either GitHub or Bitbucket VCS.

I hope this helps!

**Comment by rosieyohannan** [comment]
I'm going to close this issue now but feel free to reopen if you require further clarification :-)
