### ISSUE TITLE
Behaviour when a run Step fails is wrong.

### ISSUE THREAD

**Issue by andreasmarkussen** [circleci/circleci-docs#4080]
# Locations
[The When Attribute](https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute)
*By default, CircleCI will execute job steps one at a time, in the order that they are defined in config.yml, until a step fails (returns a non-zero exit code). After a command fails, no further job steps will be executed.*

# Details
It states that a failing step makes no further steps to be run, however in our configration (Version 2.1 .circleci/config.yml) we have multiple `run:` steps in the `steps:` section, and if one fails the others continue. As they should.

**Comment by andreasmarkussen** [comment]
Below is a picture from our pipeline. 
So that it is visible, that it runs no matter if the preceding job failed. 
![image](https://user-images.githubusercontent.com/6911804/72889792-cb6e5c80-3d10-11ea-9cac-0981bf4deea3.png)

**Comment by teesloane** [comment]
Hi @andreasmarkussen , before I make a change to the docs, do you mind reporting what kind of error code is being reported by the failing step in your config that you posted in the screenshot ("Run instrumented cucumber test on Firebase Test Lab")? 

I ran a test on a repository of mine where a binary purposefully fails on execution; it halts the entire pipeline as our docs describe because it throws a non-zero exit code:

![image](https://user-images.githubusercontent.com/12987958/72939058-fb256080-3d20-11ea-9532-d04fc4716b65.png)


Even thought there are additional steps:

![image](https://user-images.githubusercontent.com/12987958/72939004-dfba5580-3d20-11ea-95dc-5edf9d73faed.png)

**Comment by teesloane** [comment]
So I got some clarification on this @andreasmarkussen:

`run` steps that follow any previously failed steps will _not run_. However, if a later `run` step has a `when` clause with a value of `always` it will override the default behaviour.

Thanks for your patience! I will update the corresponding docs to make some clarifications. Cheers!
