### ISSUE TITLE
Scheduled jobs doesn't appear in CircleCI new UI (Nor in the v2 API)

### ISSUE THREAD

**Issue by pautorrents** [circleci/circleci-docs#4133]
# Description
Scheduled jobs doesn't appear in CircleCI new UI (Nor in the v2 API).

# Location
I was working with the Circle CI v2 API, and I realised I was not getting all the workflows for a specific pipeline. That specific pipeline has 2 workflows: One that gets triggered on push, and another one that gets triggered on a CRON schedule. I was only receiving the ones that ran on push.

Later on, using the new UI, I realized that there is no way to see them anyways in the UI.

The only way of getting information about scheduled pipelines is with the Insights endpoint (`/insights/{{project-slug}}/workflows`) of the Circle CI v2 API. But with this API endpoint it is only possible to obtain aggregated data, not the details of each individual pipeline.

# Steps to Reproduce
1. Create a project in Github
2. Add CircleCI config file (`.circleci/config.yml`)
3. In the CircleCI config file, add two workflows: One that triggers on push and one that triggers on CRON schedule
4. Execute both in CircleCI
5. Call Circle CI v2 API's `/project/{{project-slug}}/pipeline` endpoint to get last pipelines for a project.

Here, you can already see that the only pipelines that you will get are the ones that were triggered on push.

**Comment by gordonsyme** [comment]
Thanks for getting in touch @pautorrents, currently workflows are scheduled, not pipelines which is why you can see data for the workflows that were scheduled but not any associated pipeline (because there isn't one).

We have work in progress to resolve this issue right now, I can't promise an exact date it will land but it will be measured in a small number of weeks.

We'll update this issue when that gets into production.

**Comment by thomasr8** [comment]
@paultorrents I am going to close this issue for now, but we will revisit this issue when it is resolved.
