### ISSUE TITLE
store_test_results with multiple paths fails

### ISSUE THREAD

**Issue by fistii** [circleci/circleci-docs#4167]
# Description
My jobs are failing right in the beginning, with the following text:

Build-agent version 1.0.27638-873fcb7b (2020-02-19T11:37:17+0000)
Configuration errors: 1 error occurred:
* step 14 store_test_results: Path is required

I got the this error in the Spin Up Environment section.

# Steps to Reproduce
I have 2 apps in the project with shared resources and tests.

In the config.yml I have the store test result configure as:
```
      - store_test_results:
          paths:
            - common/build/test-results
            - appOne/build/test-results
            - appTwo/build/test-results
```

In the last 24 hours this setup stopped working. If I have only one path then it is fine.

**Comment by rosieyohannan** [comment]
Hi @fistii! Thanks for getting in touch. Firstly, the required key for `store_test_results` is `path`, rather than `paths`. Also, we’ve retired an undocumented option to specify a list of paths here, so we suggest you pass a single path. If you want to do this in one go, you can copy these files into one directory first. Let me know if this helps ☺️

**Comment by fistii** [comment]
Hi @rosieyohannan! Thanks for the quick reply 😃 . After separating it in different `store_test_results` and using just the `path` it worked.
