### ISSUE TITLE
Scheduled worflows stop after inactivy on repo

### ISSUE THREAD

**Issue by AntoineAugusti** [circleci/circleci-docs#4173]
# Missing Information
It seems scheduled worflows don't run after a few weeks without commits on the Git repo. This is a behaviour I've discovered which doesn't seem to be documented. I don't know the exact conditions of this feature.

# Already Looked
I've looked at https://support.circleci.com/hc/en-us/articles/115015481128-Scheduling-jobs-cron-for-builds-

# Potential Locations
The existing page seems an appropriate place

**Comment by rosieyohannan** [comment]
Hey @AntoineAugusti, thanks for getting in touch about this. Scheduled workflows should *not* stop running due to periods of inactivity. I have checked with engineering and we think it's possible your scheduled workflow could have been affected by some work that was recently done on our scheduled workflows feature internally, and so this will not happen again. Of course please get straight back in touch if you experience the problem again. ☺️

**Comment by AntoineAugusti** [comment]
Thanks for the quick reply. I've experienced this twice, that's why I assumed it was a feature.

I'll get in touch with support if I experience it again

**Comment by rosieyohannan** [comment]
Thanks for reporting that, I'll pass it on.
