### ISSUE TITLE
RE: jekyll/_docs/build-artifacts.md

### ISSUE THREAD

**Issue by 360itsolution** [circleci/circleci-docs#441]
I have an uploads folder on my production server.

Here is my cirecle.yml file.

The contents of the uploads folder is getting wiped out when I push to the production server.  Is there another way to keep a custom folder full of files to not be overwritten on each push?

machine:
  ruby:
    version: 2.3.1
  node:
    version: 6.1.0

dependencies:
  cache_directories:
    - node_modules
  override:
    - gem install capistrano --version 3.5.0
    - gem install capistrano-npm
    - npm install

test:
  override:
    - npm run lint

general:
  artifacts:
    - "uploads" # relative to the build directory

deployment:
  staging:
    branch: dev
    commands:
      - cap staging deploy

**Comment by felicianotech** [comment]
I'm assuming this is Capistrano? Maybe ask them how their deploy command works? Might be doing a wipe before sending things over, similar to how `rsync` might work with `--delete`.

This type of question is troubleshooting and belongs on [CircleCI Discuss](https://discuss.circleci.com/) where the community can help you rather than here where Doc corrections should go.
