### ISSUE TITLE
Contexts have been removed in the new UI

### ISSUE THREAD

**Issue by timothyclarke** [circleci/circleci-docs#4411]
# Locations
https://circleci.com/docs/2.0/contexts/#creating-and-using-a-context

# Details
The settings cog (on the left of the page) takes you directly to plan usage and billing. There are no links to contexts.
To get to a context you must edit a build eg `https://circleci.com/gh/<org>/<repo>/edit` and from there click the org settings link `https://circleci.com/gh/organizations/<org>/settings` to be able to view contexts
`https://circleci.com/gh/organizations/<org>/settings#contexts`

Edit This may be due to switching between new and old ui

**Comment by rosieyohannan** [comment]
Hey @timothyclarke thanks for getting in touch. I can't recreate the problem you describe....

I see two separate links in the sidebar, one for plans and billing info, and one that takes me direct to Contexts - Organization settings. I wonder if you experienced an anomaly during a UI update or, as you suggest, a strange behaviour due to UI switching? 

<img width="299" alt="Screenshot 2020-05-29 at 08 06 25" src="https://user-images.githubusercontent.com/24589403/83231431-637ac780-a183-11ea-984f-84e5e095fc45.png">

Would you mind checking you see the same side bar options shown in my screengrab?

Thanks! ☺️

**Comment by timothyclarke** [comment]
Hi @rosieyohannan I also raised a support ticket surrounding this.
I am using the old UI and the only settings option there takes you directly to the Plan option. Perhaps it's just a case of adding a note stating you need to be on the new UI until the old UI is removed.

**Comment by rosieyohannan** [comment]
@timothyclarke ah I see now, thanks for confirming how to reproduce this issue. I will add a note to reflect the problem. Thanks!!
