### ISSUE TITLE
Search doesn't render updated results when typing quickly

### ISSUE THREAD

**Issue by aaronstillwell** [circleci/circleci-docs#4522]
# Description
Sometimes when you search the docs quickly the page doesn't actually update the results to match the most recent query.

Here's an example of a query that I've quickly typed into the search bar:
<img width="1077" alt="Screenshot 2020-07-06 at 14 56 40" src="https://user-images.githubusercontent.com/6533711/86601507-537fb000-bf99-11ea-83d1-d0ac282229db.png">

Notice how despite searching for "orbs" - we're only seeing results for the query "o"

If we remove a letter and add one back, the page updates:
<img width="1070" alt="Screenshot 2020-07-06 at 14 57 19" src="https://user-images.githubusercontent.com/6533711/86601559-62666280-bf99-11ea-8978-64fff8f4e5ab.png">

# Location
Any page.

# Steps to Reproduce
Quickly type something into the search bar.

**Comment by aaronstillwell** [comment]
The following lines look suspicious to me

https://github.com/circleci/circleci-docs/blob/a2e775f4554d2fc1969893269e4ac142a6cb32d3/src-js/instantsearch.js#L60-L66

Does anyone know why we debounce at all? This isn't standard practice across similar Algolia implementations. Further, the additional `setTimeout` is asking for problems.

**Comment by rosieyohannan** [comment]
Maybe @trevor-circleci will have some insight?

**Comment by trevor-circleci** [comment]
@aaronstillwell and @rosieyohannan 

Does the document never refresh after that initial delay? I cannot replicate this behavior. There is occasionally a lag, but it does resolve within a second or less for me. However, the lag might vary depending on your region, or your computer setup (adblockers, unknown variables, etc). It's possible that a slower API response is affecting you all in the UK differently.

As for the debounce: we don't want to query the API with every keystroke as it would cause potential performance issues. The debounce above ensures that we only query the API when there is a 500 millisecond pause in typing so as to not overload the API. You can find the documentation covering this here: https://www.algolia.com/doc/guides/building-search-ui/going-further/improve-performance/js/#debouncing . So it is a standard practice, it not widely implemented.

However, our current implementation is pretty dated, and it looks like Algolia has updated it's API since we wrote this. It may make sense to update our implementation so it can mirror the example in docs more. Moreover, I'm not sure the nested setTimeout is necessary with how this debounce is implemented. It may make sense to remove it, and could fix your issue. But I wouldn't know if it was safe to remove without digging in and experimenting a bit. 

Hope this helps. Let me know if you need anything else and I'll do my best to oblige.

**Comment by rosieyohannan** [comment]
I've been experiencing this quite a but recently. One example: searching for DLC gives results for just 'd' - no mention of DLC:

<img width="974" alt="Screenshot 2020-08-14 at 12 14 47" src="https://user-images.githubusercontent.com/24589403/90244046-eaa51680-de27-11ea-8f80-a5d59a66d52b.png">

but then after a pause and deleting the 'c' I get the result I want 🙃 :

<img width="980" alt="Screenshot 2020-08-14 at 12 15 01" src="https://user-images.githubusercontent.com/24589403/90244086-f8f33280-de27-11ea-888a-419a02d1701d.png">

**Comment by thomasr8** [comment]
Hi @aaronstillwell : I see that our search has improved lately. Should I go ahead and close this issue for now, or keep it open if you want to make some more changes?

**Comment by teesloane** [comment]
Our search has definitely improved; I see no noticeable lag with the latest development. Feel free to open as necessary, however.
