### ISSUE TITLE
Failed when followed `Debugging Container ID Cannot Be Mapped to Host ID Error`

### ISSUE THREAD

**Issue by ammaratef45** [circleci/circleci-docs#5144]
I get this error when trying to run my workflow
```
CircleCI was unable to start the container because of a userns remapping failure in Docker.

This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.

Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: CircleCI was unable to start the container because of a userns remapping failure in Docker.

This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.

Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: failed to register layer: Error processing tar file(exit status 1): Container ID 397546 cannot be mapped to a host ID
```

Following [this guide](https://circleci.com/docs/2.0/high-uid-error/) I tried running `find / \( -uid 1000000 \)  -ls 2>/dev/null` and the result was empty

This is my docker file
```
FROM ammaratef45/flutter:v2

RUN flutter upgrade && chown -R root:root /root
```

Note: The base image `flutter:v2` works normally

**Comment by teesloane** [comment]
Hey @ammaratef45 ! Based on your [thread that](https://github.com/ammaratef45/dart_stack/pull/20#issuecomment-795884159) automatically linked with this issue, it looks like you folks got things working. Can we close this understanding that it was an upstream image issue? Thanks!

**Comment by ammaratef45** [comment]
We ended up using a different docker image and I'd love to understand the problem as using a different image will not be a solution every time

**Comment by teesloane** [comment]
Hi @ammaratef45 . Our docs state that "This UID/GID must be in the range of 0 - 65535".  If I'm understanding the situation, the container error you posted above mentioned a container id of `397546` which is out of range. 

I was doing some research and found your previous similar issue in this [thread](https://github.com/adamantium-architects/docker-flutter/issues/1). If what you posted above is the entire contents of your dockerfile, then perhaps the  `RUN flutter upgrade && chown -R root:root /root`  is somehow changing the id values and putting them out of range somehow. In the [previous thread it seemed](https://github.com/adamantium-architects/docker-flutter/issues/1#issuecomment-466909068) that an upgraded package via flutter doctor was causing the issue.

 Anyway, I since this is an upstream issue and our docs already cover the reason for failure I'll close this. Please feel free to re-open with additional information / if the the issue persists and does not appear to be an upstream issue.
