### ISSUE TITLE
Setting up schedules with dynamic configuration

### ISSUE THREAD

**Issue by chenglim-glu** [circleci/circleci-docs#5309]
# Missing Information
It is not clear how to set up schedules when using dynamic configuration.  Does it even work?

# Already Looked
Tried searching the internet, but have not found anybody else who have asked about this.

# Potential Locations
The documentation for dynamic configuration should cover how to set up schedules with maybe an example.  Suppose one can set up a schedule (I haven't been able to do this) through a dynamic configuration, how does a schedule become disabled?  Do all new dynamic configurations result in all old schedules being removed?

**Comment by annabaker** [comment]
Hi, thank you for raising this concern. Due to the way the app handles schedules, there currently isn't a very efficient way to achieve this. However, we are planning on releasing additional functionality in the near future that will allow this to be possible. I will close this, as the new documentation that will be released when the mentioned functionality is complete will hopefully cover some examples.
