### ISSUE TITLE
RE: jekyll/_docs/environment-variables.md

### ISSUE THREAD

**Issue by antony** [circleci/circleci-docs#68]
Your document makes it clear that you can't pragmatically export environment variables using ```EXPORT``` or similar.

What it doesn't tell you though is alternative strategies where you need to do this.

For instance I build a docker image, and then get the tag ID using ```docker images -q repo/build:tag```

I then use that tag ID to create two more tags. Or at least I would, but I can't set a dynamic variable using the command above.

So right now I'm thinking of echoing it to a file on disk, and then catting that file back when I need it. A little messy and non-obvious.

Do you have a better solution than this? Could it be documented here?

**Comment by felicianotech** [comment]
What is tagging the image in the first place? Normally when I create tags I use latest and/or the commit hash. The hash is already available in a env variable in Circle so I would use that.

For other persistent cases, if it makes sense, I use a shell script for which you can export a variable within that script for all commands. Otherwise, yes a temp file would do the trick. Caching the file for use across builds is useful too.

I would love to learn more about your use case, and hopefully get more feedback from people on here and we can go ahead and modify this page to include examples as you mentioned.

**Comment by felicianotech** [comment]
@antony Would you be able to provide a response?

**Comment by antony** [comment]
Hi @felicianotech 

Apologies for not replying sooner, been a bit snowed under.

The image I'm building is being tagged in the `deploy:` block, and I was using the generated image ID to further tag the image for the deployed servers.

I think using the CIRCLE_SHA or the commit hash would work equally well in this instance - hadn't thought of that! So yeah, perhaps this persisting of env variables isn't necessary at all.

Cheers,
Antony

**Comment by felicianotech** [comment]
Okay no worries. If you think of another use case you can always create a new feature request in https://discuss.circleci.com.

Thanks for the response. Have a good one.
