### ISSUE TITLE
Make Headings clickable anchors

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#73]
[This jekyll issue](https://github.com/jekyll/jekyll/issues/2690) suggests you can get this for free with some Markdown processors, like Redcarpet.

**Comment by felicianotech** [comment]
I'd really hate to switch from Kramdown as that'll be an extra dependency. Kramdown (what is used now) is included by default.

I was thinking of adding the link icon to the right of the header like most doc websites have. What do you think? An example is how Stripe does it: https://stripe.com/docs/checkout/tutorial

But with the chain link icon instead of a literal anchor.

**Comment by eric-hu** [comment]
The side anchor link works.  I think as long as it's automatically generated instead of requiring the markdown writer to insert a link, that goes a long way in utility.
