### ISSUE TITLE
--timings-type Valid timing types are not documented correctly

### ISSUE THREAD

**Issue by lukeca362** [circleci/circleci-docs#8660]
# Locations
[--timings-type Valid timing types](https://circleci.com/docs/parallelism-faster-jobs/#how-test-splitting-works)

# Details
Incorrect:
- name - test name
- classname class name
- file - file name

Correct:
- **testname** - test name
- classname class name
- **filename** - file name
- **autodetect** - autodetect

I discovered this when I got the error:
```
Error: invalid argument "name" for "--timings-type" flag: unknown timings type, allowed values are "filename", "classname", "testname", and "autodetect"
```

**Comment by rosieyohannan** [comment]
Hey @lukeca362 thank you so much for this report and your PR.

I think what's happening here is due to a recent change in the docs. Our test splitting examples now use the `circleci tests run` command rather than `circleci tests split`. This change was made to enable people to get set up for using the [Rerun failed test](https://circleci.com/docs/rerun-failed-tests/)s feature, which requires the `tests run` command. 

The `--timings-type` options are slightly different between the two commands

**Comment by lukeca362** [comment]
@rosieyohannan Ah, thank. Please close if you don't think is needed anymore.
