### ISSUE TITLE
Argument Validation for circleci tests split

### ISSUE THREAD

**Issue by sshaw** [circleci/circleci-docs#8895]
# Description

Invalid `--timings-type` option was passed to `circleci tests run`. This resulted in the timings not being found. An invalid argument should result in a non-zero exit code, not execution of the command.

# Location

Is there even online documentation for `circleci tests run`'s arguments? I had to SSH in and run `--help` 😕 

# Steps to Reproduce

We were splitting test as follows: 

```
circleci tests run --command="something amaaaaaazing" --split-by=timings  --timings-type=name
```
Note the `--timings-type=name`. This is incorrect and should be `filename`.

**Comment by rosieyohannan** [comment]
Hi! So I've checked our docs on this and what we have listed here for `circleci tests run` should be correct: https://circleci.com/docs/parallelism-faster-jobs/#the-tests-run-command

I have also asked that we consider adding the help for the test splitting commands to the local CLI help and here: https://circleci-public.github.io/circleci-cli/. They are not currently included because those commands are only actually available when using the CLI in a build.

If you are still having issues feel free to reopen.
