### ISSUE TITLE
No description how to prioritize the deployment build.

### ISSUE THREAD

**Issue by tioteath** [circleci/circleci-docs#930]
This issue is about <https://circleci.com/docs/2.0/configuration-reference/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/configuration-reference.md>)

Having no way to prioritize the deployment build makes the deployment feature somehow useless even for the small team. In order to make it useful, we need the ability to make sure the deployment build never gets into queue, i.e. at least one container should be always reserved for the specific (deployment) branch(es) only.

**Comment by felicianotech** [comment]
Hi,

There isn't a description at the moment because this isn't something you can do with 2.0 (at least for now). This is a feature request. I'd suggest making a feature request in CircleCI Discuss. Here's a direct link to the 2.0 feature request topic: https://discuss.circleci.com/c/circleci-2-0/2-0-feature-requests
